#!/bin/sh

echo "Number of iterations:  `wc -l fields.txt`"

cd ../skycover
echo
# M3 gives optimistically good results because there are lots of shadowed configurations which abort early.  In the probe software presumably all commanded configurations will have been prechecked by the OCS before being sent to AGWS
#echo M3
#time ./agwsvalid --m3 --boolonly < ../agwsbench/fields.txt > /dev/null
echo 
echo DGNF
time ./agwsvalid --dgnf --boolonly < ../agwsbench/fields.txt > /dev/null
echo
echo DGWF
time ./agwsvalid --dgwf --boolonly < ../agwsbench/fields.txt > /dev/null
